# Generated by Django 4.0.1 on 2022-01-11 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_alter_film_rate_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_rate',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
